[package]
name = "vmod_rers"
version = "0.0.1"
edition = "2021"

[build-dependencies]
varnish = { path = "../varnish-rs/" }
varnish-sys = { path = "../varnish-rs/varnish-sys" }

[dependencies]
varnish = { path = "../varnish-rs/" }
varnish-sys = { path = "../varnish-rs/varnish-sys" }
regex = "1.5"
regex-cache = "0.2.1"

[lib]
crate-type = ["cdylib"]
