[package]
name = "vmod_rers"
version = "0.0.5"
edition = "2021"

[build-dependencies]
varnish = "0.0.12"
varnish-sys = "0.0.12"

[dependencies]
varnish = "0.0.12"
varnish-sys = "0.0.12"
regex = "1.5"
lru = "0.7.1"

[lib]
crate-type = ["cdylib"]
