[package]
name = "vmod_rers"
version = "0.0.2"
edition = "2021"

[build-dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "29d594fe4a7190148965e01ee149cc1660467614" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "29d594fe4a7190148965e01ee149cc1660467614" }

[dependencies]
varnish = { git = "https://github.com/gquintard/varnish-rs", rev = "29d594fe4a7190148965e01ee149cc1660467614" }
varnish-sys = { git = "https://github.com/gquintard/varnish-rs", rev = "29d594fe4a7190148965e01ee149cc1660467614" }
regex = "1.5"
lru = "0.7.1"

[lib]
crate-type = ["cdylib"]
