[package]
name = "vmod_rers"
version = "0.0.1"
edition = "2021"

[build-dependencies]
varnish = "0.0.5"
varnish-sys = "0.0.5"

[dependencies]
varnish = "0.0.5"
varnish-sys = "0.0.5"
regex = "1.5"
regex-cache = "0.2.1"

[lib]
crate-type = ["cdylib"]
