[package]
name = "vmod_rers"
version = "0.0.4"
edition = "2021"

[build-dependencies]
varnish = "0.0.9"
varnish-sys = "0.0.9"

[dependencies]
varnish = "0.0.9"
varnish-sys = "0.0.9"
regex = "1.5"
lru = "0.7.1"

[lib]
crate-type = ["cdylib"]
